"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { FilesetResolver, PoseLandmarker } from "@mediapipe/tasks-vision";
import { BellOff, Camera, Check, ChevronRight, CirclePause, Eye, EyeOff, Gauge, Info, Leaf, Move3D, Play, RefreshCw, Settings2, ShieldCheck, Sparkles, TimerReset, Volume2, VolumeX, X } from "lucide-react";
import { Switch } from "@/components/ui/switch";
import { Slider } from "@/components/ui/slider";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Baseline, Landmark, PostureFeatures, PosturePattern, calibrate, canAlert, classifyPosture, createScoreSmoother, extractFeatures, postureScore, smoothFeatures, smoothPostureScore } from "@/lib/posture-analysis";

type SourceMode = "idle" | "loading" | "camera" | "demo" | "error";
type TrendPoint = { score: number; label: string };
const MODEL_URL = "https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task";
const WASM_URL = "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm";
const LINKS = [[11,12],[11,13],[13,15],[12,14],[14,16],[11,23],[12,24],[23,24]];
const patternCopy: Record<PosturePattern, { title: string; body: string }> = {
  "forward-head": { title: "Try a small reset", body: "You may be leaning forward. Bring your screen closer if that feels comfortable." },
  slouching: { title: "Try a small reset", body: "Your upper body has shifted from your baseline. Settle into a comfortable position." },
  "uneven-shoulders": { title: "Try a small reset", body: "One shoulder may be sitting higher. Let both shoulders soften." },
  stillness: { title: "Time for a movement break", body: "You have been fairly still. A brief stretch or walk may feel good." },
};

function formatTime(total: number) { const m=Math.floor(total/60),s=total%60; return `${m}:${String(s).padStart(2,"0")}`; }

function mockLandmarks(t: number): Landmark[] {
  const p=Array.from({length:33},()=>({x:.5,y:.5,z:0,visibility:1}));
  const sway=Math.sin(t/4200)*.006, lean=Math.max(0,Math.sin(t/9000))*.025;
  p[7]={x:.465+sway,y:.27+lean,z:-.12-lean,visibility:1}; p[8]={x:.535+sway,y:.27+lean,z:-.12-lean,visibility:1};
  p[11]={x:.39+sway,y:.45+lean*.45,z:-.02,visibility:1}; p[12]={x:.61+sway,y:.45+lean*.45+Math.max(0,Math.sin(t/13000))*.012,z:-.02,visibility:1};
  p[13]={x:.34,y:.58,z:0,visibility:1};p[14]={x:.66,y:.58,z:0,visibility:1};p[15]={x:.33,y:.72,z:0,visibility:1};p[16]={x:.67,y:.72,z:0,visibility:1};p[23]={x:.43,y:.77,z:.02,visibility:1};p[24]={x:.57,y:.77,z:.02,visibility:1}; return p;
}

function Sparkline({data}:{data:TrendPoint[]}) {
  const points=data.length>1?data:[{score:92,label:""},{score:92,label:""}];
  const path=points.map((p,i)=>`${(i/(points.length-1))*100},${38-(p.score/100)*32}`).join(" ");
  return <svg className="trend-chart" viewBox="0 0 100 42" preserveAspectRatio="none" role="img" aria-label="Posture wellness indicator over this session"><defs><linearGradient id="trend-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#38bda8" stopOpacity=".28"/><stop offset="1" stopColor="#38bda8" stopOpacity="0"/></linearGradient></defs><path d={`M ${path} L 100,42 L 0,42 Z`} fill="url(#trend-fill)"/><polyline points={path} fill="none" stroke="#43c7b2" strokeWidth="1.6" vectorEffect="non-scaling-stroke"/></svg>;
}

function playGentleChime(context: AudioContext | null) {
  if (!context) return;
  void context.resume();
  const start=context.currentTime+.01;
  [440,586,740].forEach((frequency,index)=>{
    const oscillator=context.createOscillator(),gain=context.createGain();
    oscillator.type="sine";oscillator.frequency.value=frequency;
    gain.gain.setValueAtTime(0,start+index*.13);
    gain.gain.linearRampToValueAtTime(.055,start+index*.12+.02);
    gain.gain.exponentialRampToValueAtTime(.001,start+index*.12+.2);
    oscillator.connect(gain).connect(context.destination);
    oscillator.start(start+index*.12);oscillator.stop(start+index*.12+.21);
  });
}

export default function Home() {
  const videoRef=useRef<HTMLVideoElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),landmarkerRef=useRef<PoseLandmarker|null>(null),rafRef=useRef(0);
  const audioContextRef=useRef<AudioContext|null>(null),belowNinetySince=useRef<number|null>(null),lastLowScoreChime=useRef(0),lowScoreLatched=useRef(false);
  const latestFeatures=useRef<PostureFeatures|null>(null),smoothed=useRef<PostureFeatures|null>(null),baselineRef=useRef<Baseline|null>(null);
  const persistenceRef=useRef<Partial<Record<PosturePattern,number>>>({}),lastAlerts=useRef<Partial<Record<PosturePattern,number>>>({}),stillSince=useRef(performance.now()),sessionStarted=useRef<number|null>(null),currentPatterns=useRef<PosturePattern[]>([]);
  const scoreSmoother=useRef(createScoreSmoother(100,performance.now()));
  const [onboarding,setOnboarding]=useState(true),[source,setSource]=useState<SourceMode>("idle"),[error,setError]=useState(""),[calibration,setCalibration]=useState(0),[isCalibrated,setIsCalibrated]=useState(false),[score,setScore]=useState(92);
  const [feedback,setFeedback]=useState<{title:string;body:string;pattern?:PosturePattern}>({title:"Ready when you are",body:"Start your camera or explore with the private demo."});
  const [paused,setPaused]=useState(false),[muted,setMuted]=useState(false),[overlay,setOverlay]=useState(true),[mirrored,setMirrored]=useState(true),[sounds,setSounds]=useState(true),[sensitivity,setSensitivity]=useState(1),[reminderMinutes,setReminderMinutes]=useState(30),[settingsOpen,setSettingsOpen]=useState(false),[resetOpen,setResetOpen]=useState(false),[resetSeconds,setResetSeconds]=useState(30),[sessionSeconds,setSessionSeconds]=useState(0),[balancedSeconds,setBalancedSeconds]=useState(0),[breaks,setBreaks]=useState(0),[trend,setTrend]=useState<TrendPoint[]>([{score:92,label:"Start"}]);
  const threshold=useMemo(()=>({head:.20/sensitivity,slouch:.075/sensitivity,shoulders:.09/sensitivity,stillness:.0035}),[sensitivity]);
  const primeAudio=useCallback(()=>{if(!audioContextRef.current)audioContextRef.current=new AudioContext();void audioContextRef.current.resume();},[]);

  const draw=useCallback((points:Landmark[])=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;const w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w*devicePixelRatio||canvas.height!==h*devicePixelRatio){canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);}ctx.clearRect(0,0,w,h);if(!overlay)return;ctx.strokeStyle="rgba(104,229,207,.72)";ctx.lineWidth=2;LINKS.forEach(([a,b])=>{const p=points[a],q=points[b];if(!p||!q)return;ctx.beginPath();ctx.moveTo(p.x*w,p.y*h);ctx.lineTo(q.x*w,q.y*h);ctx.stroke();});ctx.fillStyle="rgba(219,255,248,.95)";[7,8,11,12,13,14,15,16,23,24].forEach(i=>{const p=points[i];if(!p)return;ctx.beginPath();ctx.arc(p.x*w,p.y*h,3.2,0,Math.PI*2);ctx.fill();});},[overlay]);

  const processPoints=useCallback((points:Landmark[],now:number)=>{const raw=extractFeatures(points,smoothed.current??undefined);if(!raw)return;const value=smoothFeatures(smoothed.current,raw);smoothed.current=value;latestFeatures.current=value;if(value.movement>threshold.stillness*2.4)stillSince.current=now;const base=baselineRef.current;if(!base||paused)return;const patterns=classifyPosture(value,base,threshold,now-stillSince.current,reminderMinutes*60_000);currentPatterns.current=patterns;const stable=smoothPostureScore(postureScore(value,base,sensitivity),scoreSmoother.current,now);scoreSmoother.current=stable.state;if(stable.display!==null)setScore(stable.display);const visibleScore=stable.state.displayed;if(sounds&&!muted&&visibleScore<90){if(belowNinetySince.current===null)belowNinetySince.current=now;const persisted=now-belowNinetySince.current>=2000;const cooledDown=now-lastLowScoreChime.current>=15_000;if(persisted&&(!lowScoreLatched.current||cooledDown)){playGentleChime(audioContextRef.current);lastLowScoreChime.current=now;lowScoreLatched.current=true;}}else if(visibleScore>=92||!sounds||muted){belowNinetySince.current=null;lowScoreLatched.current=false;}const sustained=patterns.filter(p=>{if(!persistenceRef.current[p])persistenceRef.current[p]=now;return now-(persistenceRef.current[p]??now)>4200;});(Object.keys(persistenceRef.current) as PosturePattern[]).forEach(p=>{if(!patterns.includes(p))delete persistenceRef.current[p];});const alert=sustained.find(p=>canAlert(p,now,lastAlerts.current,45_000));if(alert&&!muted){lastAlerts.current[alert]=now;setFeedback({...patternCopy[alert],pattern:alert});if(sounds)playGentleChime(audioContextRef.current);}else if(!patterns.length)setFeedback({title:"Looking balanced",body:"You are close to your comfortable baseline."});},[muted,paused,reminderMinutes,sensitivity,sounds,threshold]);

  const beginCalibration=useCallback(()=>{const samples:PostureFeatures[]=[];setIsCalibrated(false);setCalibration(5);setFeedback({title:"Find your neutral",body:"Sit in a comfortable, natural position while we learn your baseline."});const collect=window.setInterval(()=>{if(latestFeatures.current)samples.push(latestFeatures.current);},100);let left=5;const tick=window.setInterval(()=>{left-=1;setCalibration(left);if(left<=0){clearInterval(tick);clearInterval(collect);const base=calibrate(samples);if(base){baselineRef.current=base;scoreSmoother.current=createScoreSmoother(100,performance.now());setScore(100);setIsCalibrated(true);sessionStarted.current=Date.now();stillSince.current=performance.now();setFeedback({title:"Looking balanced",body:"Baseline saved. We will compare gentle changes to this position."});}else setFeedback({title:"We could not see you clearly",body:"Make sure your head and shoulders are visible, then try again."});}},1000);},[]);
  const startDemo=useCallback(()=>{primeAudio();setOnboarding(false);setSource("demo");setError("");const initial=extractFeatures(mockLandmarks(0));if(initial){smoothed.current=initial;latestFeatures.current=initial;}window.setTimeout(beginCalibration,300);},[beginCalibration,primeAudio]);
  const startCamera=useCallback(async()=>{primeAudio();setOnboarding(false);setSource("loading");setError("");if(!navigator.mediaDevices?.getUserMedia){setSource("error");setError("This browser does not support camera access.");return;}try{const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},facingMode:"user"},audio:false});if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play();}const vision=await FilesetResolver.forVisionTasks(WASM_URL);landmarkerRef.current=await PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:MODEL_URL,delegate:"GPU"},runningMode:"VIDEO",numPoses:1,minPoseDetectionConfidence:.55,minTrackingConfidence:.55});setSource("camera");window.setTimeout(beginCalibration,350);}catch(e){const denied=e instanceof DOMException&&(e.name==="NotAllowedError"||e.name==="PermissionDeniedError");setSource("error");setError(denied?"Camera permission was denied. Enable it in browser settings or use demo mode.":"We could not start the camera. Demo mode is still available.");}},[beginCalibration,primeAudio]);

  useEffect(()=>{if(source!=="camera"&&source!=="demo")return;let last=-1;const loop=(now:number)=>{if(source==="demo"){const pts=mockLandmarks(now);draw(pts);processPoints(pts,now);}else if(videoRef.current&&landmarkerRef.current&&videoRef.current.readyState>=2&&videoRef.current.currentTime!==last){last=videoRef.current.currentTime;const result=landmarkerRef.current.detectForVideo(videoRef.current,now);if(result.landmarks[0]){draw(result.landmarks[0]);processPoints(result.landmarks[0],now);}}rafRef.current=requestAnimationFrame(loop);};rafRef.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(rafRef.current);},[draw,processPoints,source]);
  useEffect(()=>{const timer=setInterval(()=>{if(!sessionStarted.current||paused)return;setSessionSeconds(s=>s+1);if(!currentPatterns.current.some(p=>p!=="stillness"))setBalancedSeconds(s=>s+1);},1000);return()=>clearInterval(timer);},[paused]);
  useEffect(()=>{const timer=setInterval(()=>{if(isCalibrated)setTrend(t=>[...t.slice(-23),{score,label:new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}]);},5000);return()=>clearInterval(timer);},[isCalibrated,score]);
  useEffect(()=>()=>{const stream=videoRef.current?.srcObject as MediaStream|null;stream?.getTracks().forEach(t=>t.stop());landmarkerRef.current?.close();void audioContextRef.current?.close();},[]);
  useEffect(()=>{if(!resetOpen)return;setResetSeconds(30);const timer=setInterval(()=>setResetSeconds(s=>{if(s<=1){clearInterval(timer);setBreaks(b=>b+1);setResetOpen(false);return 30;}return s-1;}),1000);return()=>clearInterval(timer);},[resetOpen]);
  useEffect(()=>{
    type ToolInput={sensitivity?:number;reminderMinutes?:number;overlay?:boolean;mirrored?:boolean;sounds?:boolean};
    type ModelContext={registerTool:(tool:object,options?:{signal?:AbortSignal})=>void|Promise<void>};
    const context=(document as Document&{modelContext?:ModelContext}).modelContext;
    if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    const register=(tool:object)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
    register({name:"configure_posture_session",title:"Configure posture session",description:"Update the visible PosturePal sensitivity, movement reminder, overlay, mirror, or sound settings.",inputSchema:{type:"object",properties:{sensitivity:{type:"number",minimum:.7,maximum:1.35},reminderMinutes:{type:"number",minimum:5,maximum:60,multipleOf:5},overlay:{type:"boolean"},mirrored:{type:"boolean"},sounds:{type:"boolean"}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Array.isArray(input))throw new Error("Settings must be an object.");const v=input as ToolInput;if(v.sensitivity!==undefined){if(v.sensitivity<.7||v.sensitivity>1.35)throw new Error("Sensitivity must be between 0.7 and 1.35.");setSensitivity(v.sensitivity);}if(v.reminderMinutes!==undefined){if(v.reminderMinutes<5||v.reminderMinutes>60||v.reminderMinutes%5)throw new Error("Reminder must be 5–60 minutes in five-minute steps.");setReminderMinutes(v.reminderMinutes);}if(v.overlay!==undefined)setOverlay(v.overlay);if(v.mirrored!==undefined)setMirrored(v.mirrored);if(v.sounds!==undefined)setSounds(v.sounds);return{status:"updated",...v};}});
    register({name:"start_guided_reset",title:"Start guided reset",description:"Open PosturePal's visible 30-second guided comfort and movement reset.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{setResetOpen(true);return{status:"started",durationSeconds:30};}});
    return()=>lifecycle.abort();
  },[]);
  const balancedPercent=sessionSeconds?Math.round(balancedSeconds/sessionSeconds*100):0,active=source==="camera"||source==="demo";

  return <main className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark"><Leaf size={19}/></div><span>PosturePal</span></div><div className="privacy-pill"><ShieldCheck size={15}/><span>On-device processing</span><span className="privacy-detail"> · Nothing recorded or uploaded</span></div><div className="top-actions"><button className="icon-button" onClick={()=>setMuted(v=>!v)} aria-label={muted?"Unmute feedback":"Mute feedback"}>{muted?<BellOff/>:<Volume2/>}</button><button className="settings-button" onClick={()=>setSettingsOpen(true)}><Settings2 size={17}/> Settings</button><div className={`live-dot ${active?"is-live":""}`}><i/>{active?(paused?"Paused":"Live"):"Offline"}</div></div></header>
    <section className="workspace"><div className="camera-card"><div className="camera-stage"><video ref={videoRef} muted playsInline className={mirrored?"mirrored":""}/><canvas ref={canvasRef} className={mirrored?"mirrored":""}/>{source==="demo"&&<div className="demo-person" aria-hidden="true"><div className="demo-head"/><div className="demo-body"/></div>}{!active&&source!=="loading"&&<div className="camera-empty"><div className={`camera-orbit ${source==="error"?"error":""}`}>{source==="error"?<X size={27}/>:<Camera size={28}/>}</div><h2>{source==="error"?"Camera unavailable":"Your private posture space"}</h2><p>{source==="error"?error:"Camera frames stay on this device and disappear when you close the tab."}</p><div>{source!=="error"&&<button className="primary" onClick={startCamera}><Camera size={17}/> Start camera</button>}<button className={source==="error"?"primary":"secondary"} onClick={startDemo}>{source==="error"&&<Play size={17}/>} {source==="error"?"Open demo instead":"Try demo"}</button></div></div>}{source==="loading"&&<div className="camera-empty"><div className="loader"/><h2>Preparing on-device pose tracking</h2><p>Your camera is connecting. No video leaves this browser.</p></div>}{active&&<><div className="frame-label"><span>{source==="demo"?"SIMULATED LANDMARKS":"CAMERA · LOCAL ONLY"}</span></div><div className="frame-corners"/><div className="camera-controls"><button onClick={()=>setOverlay(v=>!v)}>{overlay?<Eye size={16}/>:<EyeOff size={16}/>} Skeleton</button><button onClick={()=>setPaused(v=>!v)}>{paused?<Play size={16}/>:<CirclePause size={16}/>} {paused?"Resume":"Pause"}</button></div></>}{calibration>0&&<div className="calibration"><div className="count-ring"><span>{calibration}</span></div><h3>Settle into your neutral posture</h3><p>Sit comfortably and look toward your screen.</p></div>}</div><div className="camera-footer"><div><span className="status-kicker">Tracking</span><strong>{isCalibrated?"Baseline active":active?"Getting ready":"Not started"}</strong></div><div className="footer-actions">{active&&<button className="text-button" onClick={beginCalibration}><RefreshCw size={15}/> Recalibrate</button>}<button className="reset-button" onClick={()=>setResetOpen(true)}><TimerReset size={16}/> Take a 30-second reset</button></div></div></div>
      <aside className="coach-column"><section className={`coach-card ${feedback.pattern==="stillness"?"break-state":""}`}><div className="coach-icon">{feedback.pattern==="stillness"?<Move3D/>:<Sparkles/>}</div><span className="eyebrow">Gentle cue</span><h1>{paused?"Feedback paused":feedback.title}</h1><p>{paused?"Pose tracking is paused. Resume whenever you are ready.":feedback.body}</p><div className="coach-actions"><button onClick={()=>setResetOpen(true)}>Start reset <ChevronRight size={16}/></button><button className="round" onClick={()=>setMuted(v=>!v)} aria-label={muted?"Unmute cues":"Mute cues"}>{muted?<VolumeX/>:<Volume2/>}</button></div></section><section className="score-card"><div className="score-head"><div><span className="eyebrow">Wellness indicator</span><h2>Live posture score</h2></div><Gauge size={20}/></div><div className="score-row"><div className="score-ring" style={{"--score":score} as React.CSSProperties}><div><strong>{isCalibrated?score:"—"}</strong><span>/ 100</span></div></div><div className="score-note"><strong>{score>=82?"Near your baseline":score>=64?"A little shifted":"Consider a reset"}</strong><span>Personal trend, not a medical measure</span></div></div></section><section className="quick-card"><div><span className="eyebrow">Quick tip</span><p>Let the chair support you. Comfort matters more than holding one “perfect” pose.</p></div><Info size={18}/></section></aside></section>
    <section className="session-grid"><div className="session-card wide"><div className="section-heading"><div><span className="eyebrow">This session</span><h2>Posture trend</h2></div><div className="legend"><i/> Wellness indicator</div></div><Sparkline data={trend}/><div className="chart-labels"><span>{trend[0]?.label||"Start"}</span><span>Now</span></div></div><div className="metrics-card"><div className="metric"><TimerReset/><span>Session time</span><strong>{formatTime(sessionSeconds)}</strong></div><div className="metric"><Check/><span>Balanced time</span><strong>{balancedPercent}%</strong></div><div className="metric"><Move3D/><span>Movement breaks</span><strong>{breaks}</strong></div></div></section>
    <footer><ShieldCheck size={15}/> PosturePal supports comfort and awareness. It does not diagnose, evaluate, or treat pain, injury, or health conditions.</footer>

    <Dialog open={onboarding} onOpenChange={()=>{}}><DialogContent className="onboarding" showCloseButton={false}><div className="onboard-art"><div className="halo h1"/><div className="halo h2"/><div className="onboard-mark"><Leaf/></div></div><DialogHeader><div className="eyebrow">Welcome to PosturePal</div><DialogTitle>Gentle posture awareness, kept private.</DialogTitle><DialogDescription>Your video is processed locally in this browser. It is never recorded, saved, or uploaded.</DialogDescription></DialogHeader><div className="promise-list"><div><ShieldCheck/><p><strong>Private by design</strong><span>Camera frames stay on your device.</span></p></div><div><RefreshCw/><p><strong>Calibrated to you</strong><span>Feedback uses your comfortable baseline, not universal body measurements.</span></p></div><div><Leaf/><p><strong>Wellness, not medicine</strong><span>For comfort and awareness only—not diagnosis or treatment.</span></p></div></div><div className="onboard-note">Do not use PosturePal to evaluate pain, an injury, or a medical condition. If you are concerned about symptoms, speak with a qualified professional.</div><div className="onboard-actions"><button className="primary" onClick={startCamera}><Camera size={17}/> Allow camera & begin</button><button className="secondary" onClick={startDemo}>Explore with demo</button></div></DialogContent></Dialog>
    <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent className="settings-modal"><DialogHeader><DialogTitle>Session settings</DialogTitle><DialogDescription>Adjust how PosturePal responds. Changes stay on this device.</DialogDescription></DialogHeader><div className="setting-row slider-row"><div><strong>Sensitivity</strong><span>{sensitivity<.9?"Gentle":sensitivity>1.15?"Responsive":"Balanced"}</span></div><Slider value={[sensitivity]} min={.7} max={1.35} step={.05} onValueChange={v=>setSensitivity(v[0])}/></div><div className="setting-row slider-row"><div><strong>Movement reminder</strong><span>{reminderMinutes} minutes</span></div><Slider value={[reminderMinutes]} min={5} max={60} step={5} onValueChange={v=>setReminderMinutes(v[0])}/></div><Setting label="Skeleton overlay" hint="Show detected joints" checked={overlay} onChange={setOverlay}/><Setting label="Mirror camera" hint="Match a familiar selfie view" checked={mirrored} onChange={setMirrored}/><Setting label="Notification sounds" hint="Chime every 15 seconds while below 90" checked={sounds} onChange={v=>{setSounds(v);if(v)primeAudio();}}/></DialogContent></Dialog>
    <Dialog open={resetOpen} onOpenChange={setResetOpen}><DialogContent className="reset-modal" showCloseButton={false}><div className="reset-animation"><div className="breathe-orbit"><Leaf/></div><span>{resetSeconds}s</span></div><DialogHeader><DialogTitle>A small reset</DialogTitle><DialogDescription>No need to hold a perfect pose. Move gently and choose what feels comfortable.</DialogDescription></DialogHeader><div className="reset-steps"><div><span>1</span><p>Relax your shoulders and unclench your jaw.</p></div><div><span>2</span><p>Bring your screen closer to eye level, if possible.</p></div><div><span>3</span><p>Sit comfortably, breathe, and take a brief movement break.</p></div></div><button className="secondary full" onClick={()=>{setBreaks(b=>b+1);setResetOpen(false);}}>Finish reset</button></DialogContent></Dialog>
  </main>;
}

function Setting({label,hint,checked,onChange}:{label:string;hint:string;checked:boolean;onChange:(v:boolean)=>void}) { return <div className="setting-row"><div><strong>{label}</strong><span>{hint}</span></div><Switch checked={checked} onCheckedChange={onChange} aria-label={label}/></div>; }
